//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool on 2014-07-11 at 1:46
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.Serialization;

namespace VKeCRM.Portal.DataTransferObjects
{
	public partial class Detail
	{
		
		[DataMember]
		public string DetailName
		{ 
			get; 
			set; 
		}
		
		[DataMember]
		public Guid Id
		{ 
			get; 
			set; 
		}
		
		[DataMember]
		public Guid MasterID
		{ 
			get; 
			set; 
		}
	}
}
