//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool on 9/15/2008 at 2:05 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKeCRM.Framework.Business.Enums
{
	/// <summary>
	/// Base table for this enum is Lookup.ExceptionErrorCode
	/// </summary>
	public enum ExceptionErrorCode
	{
        ApplicationSettingNotFound = 1,
        ContentExists = 2,
        ContentListNotFound = 3,
        ContentNotFound = 4, 
        ContentRevisionNotFound = 5,
        IncorrectPassword = 6,
        MemberNotFound = 7,
        MemberPictureNotFound = 8,
        MemberPortfolioNotFound = 9,
        MemberProfileNotFound = 10,
        StockMasterNotFound = 11,     
        StarsRatingNotFound = 12,
        QuoteWatchListNotFound = 13,
        MessageNotFound = 14,
		MessageAttachmentNotFound = 15,
		TradeNoteNotFound = 16,
		InvalidScreenNameFormat = 17,
		InvalidUserNameFormat = 18,
		RestrictedScreenName = 19,
		RestrictedUserName = 20,
		DuplicateApplicationSetting = 21,
		RequiredPropertyNotSet = 22,
		InvalidApplicationSettingValue = 23,
		OneMoreRuleIsMatch = 24,
		ActivityFeedSettingsNotFound = 25,
		SymbolLastFiveDaysTradesNotFound = 26,
		SymbolPortfolioPerformanceSummaryNotFound = 27,
		SymbolLastOneDayTradesNotFound = 28,
		SymbolHoldingRankingNotFound = 29,
		CapsTickerNotFound = 30,
		SecurityQuestionNotFound = 31,
		AuditEventNotFound = 32,
		CreateMembershipUserFailed = 33,
		ProviderError = 34,
		RequiredFieldIsEmpty = 35,
		RequiredParameterIsEmpty = 36,
		ResetPasswordFailed = 37,
		GetVKeCRMMemberFailed = 38,
		ActivityFeedSettingsCreateFailed = 39,
		SecondaryEMailCanNotEqualPrimaryEMail = 40,
		InvalidEMailAddress = 41,
		UpdateEMailAddressFailed = 42,
		ValueMustNotEqual = 43,
		MemberServiceSubscriptionNotFound = 44,
		UpdateMemberServiceSubscriptionFailed = 45,
		EmailAddressAlreadyExists = 46,
		InvalidSubscriptionState = 47,
		FormNotFound = 48,
		FormAuditNotFound = 49,
		JobServerNotFound = 50,
		GroupNotExists = 51,
		ExceedMaxiumNoticeCount = 52,
		ExceedMaxiumRoadblockCount = 53,
		
		SecurityUpgradeSecurityQuestionSameAsCurrent = 54,
		SecurityUpgradeSecurityAnswerSameAsCurrent = 55,

		DuplicateBlogName = 100,
		DuplicatePostBody = 101,
		DuplicatePostName = 102,
		ExceedFormMaxNumberOfRetries = 103,
		CreateCommunityServerUserFailed = 104,
        ExceedMaxWatchListPositionCount = 135,
        ExceedMaxWatchListCount = 136,

		DuplicateUserName = 500,
		DuplicateScreenName = 501,
		DuplicateSendAndRecipientMember = 502,
		DuplicateEmailAddress = 503,
		DuplicateProviderUserKey = 504,
		ConvertSymbolFailed = 505,
		DuplicateMemberServiceSubscription = 506,
		ConflictBetweenComplimentaryAndEndDate = 507,
		DuplicateGroupName=508,
		JobServerInUsing = 509,
		WatchListNotFound = 510,
		PositionIdNotFound = 511,
		PositionIdDuplicate = 512,
		WatchListSymbolRepeat = 513,

		InvalidAnswer = 600,
		InvalidCharacterField = 601,
		InvalidEmailAddress = 602,
		InvalidPassword = 603,
		InvalidProviderUserKey = 604,
		InvalidQuestion = 605,
		InvalidUserName = 606,
		AccountMappingCannotbeFoundException = 607,

        //CMS Exceptions
        EnvGroupIdOutofRegionException = 701,
        ForbidUpdateThisTypeContentException = 702,


		// WCF Communication Exceptions
		SecurityException = 1001,
		CommunicationObjectFaultedException = 1002,
		MessageSecurityException = 1003,
		TimeoutException = 1004,
		CommunicationException = 1005,
		ObjectDisposedException = 1006,

		// Data Access Execution Exceptions
		DataAccessExecutionException = 2001,

		UnknownException = 32000,
		LoggerManagerNotInitialized = 32001,
		ErrorMessageNotFound = 32002,


		//Penson API related exceptions
        PensonServiceException = 3000,
		PensonUserAlreadyExists = 3001,
		QuoteUserAlreadyExists = 3002,        
        PensonFailedUpdateOrder = 3003,
        PensonInvalidUser = 3004,
		StateNotMatch = 3005,
        PensonFailedConfirmOrder = 3006,
        PensonFailedSubmitOrder = 3007,
        PensonFailedCancelOrder = 3008,

        //Apollo API related exceptions, begin with 3200. 
        TradingServiceException = 3200,
        TradingFailedUpdateOrder = 3203,
        TradingInvalidUser = 3204,
        TradingFailedConfirmOrder = 3206,
        TradingFailedSubmitOrder = 3207,
        TradingFailedCancelOrder = 3208,

		// ***************************************************
		// For penson error code, begin with 5000. 
		// ***************************************************        
        Normal = 0,
        NoDataFound = 5000,
        GerneralError = 5001,
        CorrespondentNotAuthorizedForAccount = 5002,
        XMLSchemaValidationFailure = 5003,
        LoginFailedInvalidDateTime = 5004,
        LoginFailedDecryptionFailure = 5005,
        LoginFailedDateTimeMissing = 5006,
        LoginFailedCustomerIDMissingorInvalid = 5007,
        LoginFailedUnauthorizedRequest = 5008,
        LoginFailedAuthorizationFailure = 5009,
        LoginFailedAuthenticationFailure = 5010,
        AccountHolderNameEmpty = 5011,
        NickNameEmpty = 5012,
        DuplicateRelationshipCreation = 5013,
        RelationshipAlreadyInCancelStatus = 5014,
        PensonZeroException = 5015,
		DataVersionNotMatch = 5016,
		CashTransferWorkflowStatusChanged = 5017,
		CashTransferCancellationFailed = 5018,
		FraudLockout = 5019,
        MemberSessionUnauthorized = 5020,

		/// <summary>
		/// Ach relationship and cash transfer
		/// </summary>
		FromAccountisRequired = 5100,
		ToAccountisRequired = 5101,
		ACHRelationshipdoesnotexistorisinactive = 5102,
		ACHTransfersuccessful = 5103,
		StartDateisrequired = 5104,
		InvalidStartDate = 5105,
		ContributionTypeisrequired = 5106,
		ContributionYearisrequired = 5107,
		ContributionYearshouldbeeithercurrentyearorpreviousyear = 5108,
		DistributionAmountisrequired = 5109,
		DistributionReasonisrequired = 5110,
		BankRoutingNumberisrequired = 5111,
		BankAccountNumberisrequired = 5112,
		ConfirmBankAccountNumberisrequired = 5113,
		BankAccountNameisrequired = 5114,
		AccountNumberandConfirmAccountNumbershouldbesame = 5115,
		ACHAuthorizationsavedsuccessfully = 5116,
		ACHAuthorizationfailed = 5117,
		PensonAccountnumberisnotvalid = 5118,
		InvalidFrequencyValidvaluesare = 5119,
		Firmisrequired = 5120,
		AccountNumberisrequired = 5121,
		Cityisrequired = 5122,
		Stateisrequired = 5123,
		AccountTypeshouldbeeitherCashorMargin = 5124,
		InvalidDeliverymethod = 5125,
		InvalidAddress = 5126,
		Beneficiarynameisrequired = 5127,
		AddressLine1isrequired = 5128,
		ZipCodeisrequired = 5129,
		ChargeToshouldbeeitherBrokerorCustomer = 5130,
		AddressTypeshouldbeeitherAlternateorThirdParty = 5131,
		CheckRequestsuccessfulTheamountwillbetransferred = 5132,
		CheckRequestsuccessfulYouraccountbalancewillbetransferred = 5133,
		SwiftNumberisrequired = 5135,
		Countryisrequired = 5136,
		BankNameisrequired = 5137,
		BankCityisrequired = 5138,
		FederalIncomeTaxWithholdingTypeisrequired = 5139,
		StateIncomeTaxWithholdingTypeisrequired = 5140,
		ForfurthercredittoAccountNumberisrequired = 5141,
		ForfurthercredittoNameisrequired = 5142,
		InvalidBankABANumber = 5143,
		ChargePrepayFeeToisrequired = 5144,
		ChargePrepayFeeTovalueshouldbeeitherBrokerorCustomer = 5145,
		Quantityisrequired = 5146,
		InvalidQuantity = 5157,
		CusipSymbolvalueisrequired = 5148,
		Invalidsecurity = 5149,
		WireTransferRequestsuccessful = 5150,
		InvalidCountry = 5151,
		SimpleIRAmorethan2yearsoldforContributionisrequired = 5152,
		SimpleIRAmorethan2yearsoldisrequired = 5153,
		InvalidDistributionType = 5154,
		InvalidDistributionReason = 5155,
		InvalidContributionType = 5166,
		SimpleIRAmorethan2yearsoldvalueshouldbeYorN = 5157,
		SimpleIRAmorethan2yearsoldforContributionshouldbeYorN = 5158,
		CashJournalsuccessful = 5159,
		InvalidFirmoraccessdenied = 50160,
		Eithertheexternalaccounttypeorthebankroutingnumberisincorrect = 5161,
		InvalidAmountAmountmustbenumeric = 5162,
		InvalidCurrencyCurrencyhastobeUSD = 5163,
		WARNINGWorkflowStateIDnotupdatedfor = 5164,
		FromAccounthastobeaPensonAccountifaccountbalanceistobetransferred = 5165,
		CashTransferNotFoundException = 5166,
		ApprovedCashTransferCannotBCancelled = 5177,

		/// <summary>
		/// no mapping and communication
		/// </summary>
		ApiCommunicationException = 5536,
		NotMappingedError = 5537,

		/// <summary>
		/// IRAAsist servie
		/// </summary>
		MissingEmptyargFirm = 6001,
		MissingEmptyargFromAccountNumber = 6002,
		MissingEmptyargTransferType = 6003,
		InvalidargTransferType = 6004,
		MissingEmptyargToAccountNumber = 6005,
		FromAccountNumberNotFound = 6006,
		ToAccountNumberNotFound = 6007,
		CorrespondentnotauthorizedforFromAccountNumber = 6008,
		CorrespondentnotauthorizedforToAccountNumber = 6009,
		ProvideeitherToorFromAccountNumberforACHTransfersnotboth = 6010,
		EitherToorFromAccountNumberrequiredforACHTransfers = 6011,
		FreeformmessagerelatedtotheFromAccount = 6012,
		FreeformmessagerelatedtotheToAccount = 6013,
		CustomerOfficeIDNotAuthorizedForFromAccount = 6014,
		CustomerOfficeIDNotAuthorizedForToAccount = 6015,

		/// <summary>
		/// SecureMailUUID service
		/// </summary>
		MissingEmptyargUUID = 6201,
		InvalidargStatementStatus = 6202,
		InvalidargConfirmStatus = 6203,
		NoexistingloginfoundfortheargUUIDprovided = 6204,
		MissingEmptyargEmailAddress = 6205,
		OneormoresignupswererequestedforwhichtheargCorrespondentIDisnoteligible = 6206,
		InvalidargEmailAddressimproperlyformatted = 6207,

		/// <summary>
		/// EmailAddress service
		/// </summary>
		argUUIDnotassociatedwiththeargCorrespondentOfficeID = 6401,

		/// <summary>
		/// CustomerStatment
		/// </summary>
		MissingEmptyAccount = 6601,
		AccountNotFound = 6602,
		WebServiceUnavailableDatabaseNotReady = 6603,
		MissingEmptysXML = 6604,
		MissingInvalidCustomerID = 6605,
		MissingInvalidCustomerOfficeID = 6606,
		MissingInvalidDateTime = 6607,
		GenericError = 6068,
		CustomerOfficeIDNotAuthorizedForAccount = 6609,

		/// <summary>
		/// CustomConfirm
		/// </summary>
		MissingEmptyargAccountNumber = 6801,
		MissingEmptyargCorrespondentID = 6802,
		UnauthorizedargCorrespondentID = 6803,
		MissingEmptyargDate = 6804,
		Notsignedupforelectronictradeconfirms = 6805,
		ConfirmnotfoundforXXXXXXXX = 6806,
		InvalidDate = 6807,
		MissingEmptyargBeginDate = 6808,
		MissingEmptyargEndDate = 6809,
		InvalidargBeginDate = 6810,
		InvalidargEndDate = 6811,
		argBeginDatecannotbegreaterthancurrentdate = 6812,
		argEndDatecannotbegreaterthancurrentdate = 6813,
		argEndDateshouldbegreaterthanargBeginDate = 6814,
		NologinfoundfortheUUIDprovided = 6815,

		/// <summary>
		/// ach relationship error
		/// </summary>
		ProblemWithXml = 7201,
		FirmEmpty = 7202,
		InvalidFirm = 7203,
		BankRoutingNumberEmpty = 7204,
		BankAccountNumberEmpty = 7205,
		BankAccountNameEmpty = 7206,
		AccountNumberAndConfirmArenotSame = 7207,
		ConfirmBankAccountNumberEmpty = 7208,
		IncorrectAmounts = 7209,
		AccountNumberProvidedIsNotValid = 7210,
		NotAuthorizedForThisAccount = 7211,
		AchAuthorizationFailed = 7212,
		AccountNumberIsRequired = 7213,
		AccountTypeIsRequired = 7214,
		AmountIsRequired = 7215,
		AfterDecimalPointShouldLessThan2digits = 7216,
		BeforeDecimalPointShouldLessThan18digits = 7217,
		AmountMustGreaterAndZero = 7218,
		AccountDoesNotExist = 7219,
		NotEligibleForAPre_Note = 7220,
		Pre_NoteProcessHasBeenInitiated = 7221,
		NotEligibleForPre_NoteConfirmation = 7222,
		DifficultyIdentifyingItsCorrespondingPreNoteTransactions = 7223,
		
		ConfirmationAmountsSubmittedAreIncorrect = 7224,
		AchRelationshipCancellationFailed = 7225,
		PreNoteConfirmationFailed = 7226,

		/// <summary>
		/// accountDetail
		/// </summary>
		CustomerIDmissingempty = 7401,
		FirmIDmissingempty = 7402,
		AccountNumbermissingempty = 7403,
		NoAchLinkAllowed = 7404,
		// == end ==

        // == Get Option Quote Exception start at 7001
        OptionQuoteNotExist = 7001,
        OptionQuoteAlreadyExist = 7011,

        //== Community API Exception
        SymbolNotExist = 8001,

		//== Group Exception
		MemberProfileNotSharing = 9001,

        SymbolNullException = 1101,

		//Crm Message Exception
		MemberIdNotFoundException=1201,
		CaseIdNotFoundException=1202,
		PensonAccountNumberNotFoundException=1203,
		MessageSubjectRequiredException=1204,
		FirstNameRequiredException=1205,
		LastNameRequiredException=1206,
		MessageBodyRequiredException = 1207,
		CreateCaseFailedException=1208,
		UpdateCaseFailedException=1209,
		CreateCaseCommentFailedException=1210,
		AuthenticateErrorException=1211,
		UnavailableCrmReplyException = 1212,
		BatchIdRequiredException = 1213,
		BatchIdAlreadyQueuedException = 1214,

		//Ip Logging Exception
		DuplicateIpAddress=2000,

        //Nexa Message Exception
        NexaTokenNotFoundException = 1300,
        NexaAccountNotFoundException = 1301,
        NexaBadErrorCode = 1302,
        NexaReceiveXmlException = 1303,

		Ola_SsnNotMatchException = 9002,
		Ola_GovernmentNotMatchException = 9003

	}
}
