//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool on 2014-07-11 at 1:47
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace VKeCRM.Portal.DataAccess.DomainObjects
{
    /// <summary>
    /// Detail domain object contains a record from the dbo.Detail table
    /// </summary>
    public partial class Detail
    {
        #region Declarations
        private string _detail;
        private Guid _id;
        private Guid _masterId;
        #endregion

        #region Properties
        public virtual string DetailName
        {
            get { return _detail; }
            set { _detail = value; }
        }
        public virtual Guid Id
        {
            get { return _id; }
            set { _id = value; }
        }
        public virtual Guid MasterID
        {
            get { return _masterId; }
            set { _masterId = value; }
        }
        #endregion
    }
}
