//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool on 2014-07-11 at 1:48
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace VKeCRM.Portal.DataAccess.DomainObjects
{
    /// <summary>
    /// Master domain object contains a record from the dbo.Master table
    /// </summary>
    public partial class Master
    {
        #region Declarations
        private Guid _id;
        private string _MasterName;
        private IList<Detail> _details;
        #endregion

        #region Properties
        public virtual Guid Id
        {
            get { return _id; }
            set { _id = value; }
        }
        public virtual string MasterName
        {
            get { return _MasterName; }
            set { _MasterName = value; }
        }
        public virtual IList<Detail> Details
        {
            get { return _details; }
            set { _details = value; }
        }
        #endregion
    }
}
