//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKeCRM.Common.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VKeCRM.Common.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an email address..
        /// </summary>
        public static string EmailValidator_EmailEmptyEmailAddress {
            get {
                return ResourceManager.GetString("EmailValidator_EmailEmptyEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address contains illegal characters..
        /// </summary>
        public static string EmailValidator_EmailHasInvalidCharacters {
            get {
                return ResourceManager.GetString("EmailValidator_EmailHasInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string EmailValidator_EnterValidEmailAddress {
            get {
                return ResourceManager.GetString("EmailValidator_EnterValidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error ({0}) not defined..
        /// </summary>
        public static string ErrorInfo_NotDefined {
            get {
                return ResourceManager.GetString("ErrorInfo_NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write log. {0}.
        /// </summary>
        public static string Logger_UnableToWriteLog {
            get {
                return ResourceManager.GetString("Logger_UnableToWriteLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto Provider is required for encrypted deserialization..
        /// </summary>
        public static string Persister_CryptoProviderRequiredForSerialization {
            get {
                return ResourceManager.GetString("Persister_CryptoProviderRequiredForSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found..
        /// </summary>
        public static string Persister_FileNotFound {
            get {
                return ResourceManager.GetString("Persister_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph type is required for serialization..
        /// </summary>
        public static string Persister_GraphTypeRequired {
            get {
                return ResourceManager.GetString("Persister_GraphTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is required for serialization..
        /// </summary>
        public static string Persister_ObjectRequired {
            get {
                return ResourceManager.GetString("Persister_ObjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to decrypt text..
        /// </summary>
        public static string Persister_UnableToDecrypt {
            get {
                return ResourceManager.GetString("Persister_UnableToDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to encrypt text..
        /// </summary>
        public static string Persister_UnableToEncrypt {
            get {
                return ResourceManager.GetString("Persister_UnableToEncrypt", resourceCulture);
            }
        }

        public static string ADAuthentication_Failed
        {
            get
            {
                return ResourceManager.GetString("ADAuthentication_Failed", resourceCulture);
            }
        }
    }
}
